module.exports = {
    FB_PAGE_TOKEN: 'EAAaoeiH215gBACmTvn0jzQWriLx9qZB5VSKd57ZA7g2tq06mhRkd2oFdAoJmzyMGPhDb37tEoifHjDjWlP8RPQuV1i1knr5YGTyXvEc5VFU1vO6ZCranP5Gr6tyrI3lpZADrvbIkZCPGHg6ypeAO6FvwfA2dn3ZAgB5gJ8JzNJOFXwk1yZANWpj',
    FB_VERIFY_TOKEN: '',
    API_AI_CLIENT_ACCESS_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: "",
};